version: '3.8'

services:
  # Server
  app:
    container_name: eshop-api
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    command: node dist/main.js
    restart: unless-stopped
    env_file: .env.staging
    depends_on:
      - database
    ports:
      - 5201:5201
    networks:
      - eshop-network

  # MySQL
  database:
    container_name: eshop-database
    # image: mysql/mysql-server:8.0.31-aarch64
    image: mysql:8.1.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      - MYSQL_ROOT_HOST=0.0.0.0
      - MYSQL_USER=hoang
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=eshop_database
    ports:
      - 3307:3306
    volumes:
      - eshop-volume:/var/lib/mysql
    networks:
      - eshop-network

  # Redis
  redis:
    container_name: eshop-redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - eshop-volume:/data/redis
    networks:
      - eshop-network

  # Nginx Web Server
  nginx:
    container_name: eshop-nginx
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./templates:/etc/nginx/templates
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - eshop-network
    environment:
      - NGINX_PORT=80

networks:
  eshop-network:
    driver: bridge

volumes:
  eshop-volume:
