name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Fetch-latest-code:
    name: Fetch latest code
    runs-on: self-hosted
    steps:
      - name: Clean Docker
        run: docker system prune -a -f
      - name: Fetch latest code
        run: |
          cd $HOME/project/eshop-api
          git pull
  Generate-Migration:
    name: Generate Migration
    runs-on: self-hosted
    needs: Fetch-latest-code
    continue-on-error: true
    steps:
      - name: Generate Migration
        run: |
          cd $HOME/project/eshop-api
          yarn install
          yarn build
          yarn migration:generate
          yarn build
          yarn migration:run
  Build:
    name: Build
    runs-on: self-hosted
    needs: Generate-Migration
    steps:
      - name: Build
        run: |
          cd $HOME/project/eshop-api 
          docker compose -f docker-compose-staging.yaml up -d --force-recreate --no-deps --build app
  Noti-for-Boss:
    name: Noti for Boss
    runs-on: self-hosted
    needs: Build
    steps:
      - name: Noti for Boss
        run: curl --location 'https://api.telegram.org/bot6363750449:AAHX_MiUKje6x6AQaC9zlCchyFKu1RY-n_c/sendMessage?chat_id=-1001591974077&text=messages-api%3A%20Build%20Success'
